languageCode = "en-uk"
title = "OldStreet.ai"
baseURL = "https://amazing-easley-5a69bf.netlify.com/"
theme = "../.."
googleanalytics = "UA-124573011-1"
#disqusShortname = "hugo-massively"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "false"

[languages]
[languages.en]
  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
